---
- name: define backstore objects for target {{ target.name }}
  targetcli_backstore:
    backstore_type: "{{ disk.type }}"
    backstore_name: "{{ disk.name }}"
    options: "{{ disk.path }}"
  with_items:
    - "{{ target.disks }}"
  loop_control:
    loop_var: "disk"
  notify:
    - save targetcli configuration

- name: create iSCSI target {{ target.name }}
  targetcli_iscsi:
    wwn: "{{ base_wwn }}:{{ target.name }}"
  notify:
    - save targetcli configuration

- name: define ACLs for iSCSI target {{ target.name }}
  targetcli_iscsi_acl:
    wwn: "{{ base_wwn }}:{{ target.name }}"
    initiator_wwn: "{{ initiator }}"
  with_items:
    - "{{ target.initiators }}"
  loop_control:
    loop_var: "initiator"
  notify:
    - save targetcli configuration

- name: assign LUNs to initiators for target {{ target.name }}
  targetcli_iscsi_lun: 
    wwn: "{{ base_wwn }}:{{ target.name }}"
    backstore_type: "{{ disk.type }}"
    backstore_name: "{{ disk.name }}"
  with_items:
    - "{{ target.disks }}"
  loop_control:
    loop_var: "disk"
  notify:
    - save targetcli configuration