---
- name: Install targetcli apt packages
  apt:
    name: "{{ item }}"
  with_items:
    - python-configshell-fb
    - python-rtslib-fb
    - targetcli-fb

- name: Add iSCSI kernel modules to /etc/modules
  lineinfile:
    dest: /etc/modules
    line: "{{ item }}"
    state: present
  with_items:
    - tcm_qla2xxx
    - iscsi_target_mod
    - tcm_usb_gadget
    - tcm_loop
  register: kernelmodules

- name: Reload kernel modules
  service:
    name: systemd-modules-load
    state: restarted
  when: kernelmodules.changed

- name: Start and enable LIO target service
  service:
    name: rtslib-fb-targetctl
    enabled: yes
    state: started
